package org.smecrow.feedback.model;

public enum Reason {
    SEM_CONEXAO, LENTIDAO, UPGRADE, TROCA_DE_LUGAR, SEGUNDO_PONTO, N2, SINAL_ALTO, CABEAMENTO, TV_BOX, EQUIPAMENTO_COM_DEFEITO, RADIO, OUTROS
}
