# Server
server.port=${PORT:8080}

# Database Local
spring.datasource.url=${DATABASE_URL:${DEV_DATABASE_URL:jdbc:postgresql://localhost:5432/feedback_dev}}
spring.datasource.username=${DATABASE_USERNAME:${DEV_DATABASE_USERNAME:postgres}}
spring.datasource.password=${DATABASE_PASSWORD:${DEV_DATABASE_PASSWORD:}}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Hikari
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# Jwt (local)
jwt.secret=${JWT_SECRET:${DEV_JWT_SECRET}}

# Cors (libera tudo local)
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:${DEV_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}}

# Logging
logging.level.root=INFO
logging.level.com.smecrow.feedback=DEBUG
